version: '3.8'

services:
  app:
    image: php:8.2-fpm
    container_name: symfony_app
    volumes:
      - ./app:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - mongodb
    networks:
      - symfony_network

  web:
    image: php:8.2-apache
    container_name: symfony_web
    ports:
      - "8080:80"
    volumes:
      - ./app:/var/www/html
      - ./apache/apache.conf:/etc/apache2/sites-available/000-default.conf
    depends_on:
      - app
    networks:
      - symfony_network
    build:
      context: ./app

  mongodb:
    image: mongo:6
    container_name: symfony_mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - symfony_network

volumes:
  mongo_data:

networks:
  symfony_network: